# Generated by Django 5.0.4 on 2024-04-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gassapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
