# Generated by Django 5.0.4 on 2024-04-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gassapp', '0004_gascustomer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gascustomer',
            name='user',
        ),
    ]
